/** Realistic Australian seed content for the AnyTrade demo database. */

export const ADMIN = {
  name: 'Marg Whitlam',
  email: 'admin@anytrade.com.au',
  password: 'Admin!2345',
}

export const DEMO_PASSWORD = 'Password!123'

export const SUBURBS = [
  { suburb: 'Parramatta', city: 'Sydney', state: 'NSW', postcode: '2150' },
  { suburb: 'Newtown', city: 'Sydney', state: 'NSW', postcode: '2042' },
  { suburb: 'Blacktown', city: 'Sydney', state: 'NSW', postcode: '2148' },
  { suburb: 'Manly', city: 'Sydney', state: 'NSW', postcode: '2095' },
  { suburb: 'Penrith', city: 'Sydney', state: 'NSW', postcode: '2750' },
  { suburb: 'Sutherland', city: 'Sydney', state: 'NSW', postcode: '2232' },
  { suburb: 'Footscray', city: 'Melbourne', state: 'VIC', postcode: '3011' },
  { suburb: 'Brunswick', city: 'Melbourne', state: 'VIC', postcode: '3056' },
  { suburb: 'Dandenong', city: 'Melbourne', state: 'VIC', postcode: '3175' },
  { suburb: 'Frankston', city: 'Melbourne', state: 'VIC', postcode: '3199' },
  { suburb: 'Chermside', city: 'Brisbane', state: 'QLD', postcode: '4032' },
  { suburb: 'Ipswich', city: 'Brisbane', state: 'QLD', postcode: '4305' },
  { suburb: 'Southport', city: 'Gold Coast', state: 'QLD', postcode: '4215' },
  { suburb: 'Norwood', city: 'Adelaide', state: 'SA', postcode: '5067' },
  { suburb: 'Fremantle', city: 'Perth', state: 'WA', postcode: '6160' },
  { suburb: 'Joondalup', city: 'Perth', state: 'WA', postcode: '6027' },
]

/** Tradespeople. `homegirl: true` seeds a Homegirls network member. */
export const TRADIES = [
  {
    name: 'Bruce Kowalski',
    business: 'Kowalski Home Handyman',
    trades: ['handyman', 'carpentry', 'plastering'],
    tagline: 'Forty years of odd jobs. No call-out fee, no surprises.',
    bio: "Started as a chippy in 1984 and have been doing handyman work around the western suburbs ever since. I'd rather do five small jobs properly in a day than one big one badly. Bring me a list — flat-packs, dodgy doors, patching, shelves, gates — and I'll knock it over in one visit.",
    suburb: 'Parramatta',
    years: 40,
    hourly: 95,
    callout: 0,
    minimum: 95,
    rating: 4.9,
    reviews: 87,
    jobs: 412,
    credits: 42,
    tier: 'MASTER',
    verified: true,
    featured: true,
    emergency: false,
    weekends: true,
    licence: 'NSW-HB-118420',
    insurer: 'CGU Trade Cover',
    abn: '51 824 753 556',
    handyman: [
      'Flat-pack furniture assembly',
      'Shelves, brackets & wall mounting',
      'TV wall mounting',
      'Door adjusting & hanging',
      'Wall patching & touch-up paint',
      'Skirting & architrave repair',
      'Fence & gate repairs',
      'Odd jobs list (by the hour)',
    ],
  },
  {
    name: 'Dimitri Alexopoulos',
    business: 'Alexopoulos Plumbing',
    trades: ['plumbing', 'bathroom-reno'],
    tagline: 'Third-generation plumber. We answer the phone at 2am.',
    bio: 'Family plumbing business since 1971. Blocked drains, hot water, burst pipes and full bathroom fit-outs. Licensed, insured and we clean up after ourselves.',
    suburb: 'Newtown',
    years: 26,
    hourly: 135,
    callout: 89,
    minimum: 180,
    rating: 4.7,
    reviews: 143,
    jobs: 690,
    credits: 61,
    tier: 'MASTER',
    verified: true,
    featured: true,
    emergency: true,
    weekends: true,
    licence: 'NSW-PL-92014',
    insurer: 'QBE Tradesman',
    abn: '72 118 904 223',
    handyman: ['Leaking taps & washers', 'Toilet & cistern repairs', 'Silicone & sealing'],
  },
  {
    name: 'Jodie Kirkland',
    business: 'Kirkland Electrical',
    trades: ['electrical', 'air-conditioning'],
    tagline: 'Licensed sparky. Straight answers, itemised quotes.',
    bio: "A-grade electrician running my own show since 2012. Power points, downlights, switchboards, safety switches and split systems. I'll tell you what you actually need, not what's easiest to sell you.",
    suburb: 'Brunswick',
    years: 15,
    hourly: 125,
    callout: 75,
    minimum: 150,
    rating: 4.9,
    reviews: 98,
    jobs: 355,
    credits: 38,
    tier: 'GUVNOR',
    verified: true,
    featured: true,
    emergency: true,
    weekends: false,
    homegirl: true,
    licence: 'VIC-EC-30117',
    insurer: 'Allianz Trades',
    abn: '38 662 017 441',
    handyman: ['Smoke alarm battery swap'],
    intro:
      "Sparky in Brunswick, 15 years in. Started as the only woman on a commercial site in Dandenong and I'm still here. Happy to talk anyone through the apprenticeship or a tricky switchboard.",
    mentor: true,
  },
  {
    name: 'Tran Nguyen',
    business: 'TN Carpentry & Decks',
    trades: ['carpentry', 'fencing'],
    tagline: 'Decks, pergolas and fences built to outlast the mortgage.',
    bio: 'Carpenter and joiner. Decking, pergolas, fencing and built-in storage. Everything gets bolted, not nailed, where it matters.',
    suburb: 'Footscray',
    years: 18,
    hourly: 110,
    callout: 0,
    minimum: 220,
    rating: 4.8,
    reviews: 64,
    jobs: 221,
    credits: 27,
    tier: 'GUVNOR',
    verified: true,
    weekends: true,
    licence: 'VIC-DB-U-48812',
    insurer: 'CGU Trade Cover',
    abn: '19 003 771 288',
    handyman: ['Decking board replacement', 'Fence & gate repairs', 'Shelves, brackets & wall mounting'],
  },
  {
    name: 'Sharon Petrakis',
    business: 'Petrakis Painting',
    trades: ['painting', 'plastering'],
    tagline: 'Prep properly or do it twice. We prep properly.',
    bio: 'Interior and exterior painting across the eastern suburbs. Two coats minimum, drop sheets everywhere, and we move the furniture back before we leave.',
    suburb: 'Manly',
    years: 22,
    hourly: 85,
    callout: 0,
    minimum: 250,
    rating: 4.6,
    reviews: 71,
    jobs: 189,
    credits: 19,
    tier: 'SUBBIE',
    verified: true,
    weekends: false,
    homegirl: true,
    licence: 'NSW-HB-204118',
    insurer: 'QBE Tradesman',
    abn: '64 227 901 033',
    handyman: ['Wall patching & touch-up paint'],
    intro:
      'Painter, 22 years. Run a crew of four out of Manly, three of us are women. Always after good subbies and happy to share supplier contacts.',
    mentor: true,
  },
  {
    name: 'Gary Whelan',
    business: 'Whelan Roofing & Guttering',
    trades: ['roofing'],
    tagline: 'Leaks found and fixed. We go up so you do not have to.',
    bio: 'Roof repairs, gutter cleaning, tile replacement and full restorations. Twenty-eight years on Sydney roofs.',
    suburb: 'Sutherland',
    years: 28,
    hourly: 120,
    callout: 95,
    minimum: 180,
    rating: 4.4,
    reviews: 52,
    jobs: 244,
    credits: 12,
    tier: 'SUBBIE',
    verified: true,
    emergency: true,
    licence: 'NSW-HB-77301',
    insurer: 'Allianz Trades',
    abn: '90 554 118 776',
    handyman: ['Gutter cleaning'],
  },
  {
    name: 'Amrit Singh',
    business: 'Singh Tiling & Waterproofing',
    trades: ['tiling', 'bathroom-reno'],
    tagline: 'Waterproofed to standard, tiled dead level.',
    bio: 'Bathrooms, splashbacks and floors. Certified waterproofer — if the membrane is wrong nothing else matters.',
    suburb: 'Blacktown',
    years: 14,
    hourly: 105,
    callout: 60,
    minimum: 220,
    rating: 4.8,
    reviews: 46,
    jobs: 167,
    credits: 24,
    tier: 'GUVNOR',
    verified: true,
    weekends: true,
    licence: 'NSW-HB-159022',
    insurer: 'CGU Trade Cover',
    abn: '23 771 044 190',
    handyman: ['Silicone & sealing'],
  },
  {
    name: 'Kelly Brennan',
    business: 'Brennan Garden & Property Care',
    trades: ['landscaping', 'cleaning', 'removals'],
    tagline: 'Mow, prune, clear out and cart away. One crew, one price.',
    bio: 'Garden maintenance, clean-ups, green waste runs and pressure washing. Regular fortnightly rounds or one-off blitzes.',
    suburb: 'Frankston',
    years: 11,
    hourly: 75,
    callout: 0,
    minimum: 90,
    rating: 4.7,
    reviews: 112,
    jobs: 480,
    credits: 33,
    tier: 'GUVNOR',
    verified: true,
    weekends: true,
    homegirl: true,
    licence: null,
    insurer: 'QBE Tradesman',
    abn: '11 908 223 647',
    handyman: ['Gutter cleaning', 'Rubbish & green waste runs', 'Garden tap & hose fittings'],
    intro:
      'Started with a trailer and a whipper snipper in 2014, now run three crews out of Frankston. Ask me anything about pricing maintenance rounds.',
    mentor: true,
  },
  {
    name: 'Vince Marchetti',
    business: 'Marchetti Concreting',
    trades: ['concreting'],
    tagline: 'Driveways, slabs and paths poured straight.',
    bio: 'Concreting since 1998. Driveways, shed slabs, paths and exposed aggregate. We form up properly and we do not chase the weather.',
    suburb: 'Ipswich',
    years: 27,
    hourly: 130,
    callout: 0,
    minimum: 800,
    rating: 4.5,
    reviews: 38,
    jobs: 142,
    credits: 8,
    tier: 'FREE',
    verified: true,
    licence: 'QLD-QBCC-1122334',
    insurer: 'Allianz Trades',
    abn: '47 660 118 992',
    handyman: [],
  },
  {
    name: 'Mia Fitzgerald',
    business: 'Fitzgerald Locksmiths',
    trades: ['locksmith'],
    tagline: 'Locked out? We are usually there inside the hour.',
    bio: 'Mobile locksmith covering the northside. Lockouts, rekeys, deadbolts, window locks and security cameras.',
    suburb: 'Chermside',
    years: 9,
    hourly: 115,
    callout: 70,
    minimum: 130,
    rating: 4.9,
    reviews: 59,
    jobs: 298,
    credits: 21,
    tier: 'SUBBIE',
    verified: true,
    emergency: true,
    weekends: true,
    homegirl: true,
    licence: 'QLD-SEC-88417',
    insurer: 'CGU Trade Cover',
    abn: '85 301 774 620',
    handyman: ['Lock & handle replacement', 'Child safety fittings'],
    intro:
      'Mobile locksmith on the Brisbane northside. A lot of my callouts are women locked out at night — happy to be on anyone’s after-hours list.',
    mentor: false,
    seeking: true,
  },
  {
    name: 'Pete Donnelly',
    business: 'Donnelly Appliance Repairs',
    trades: ['appliance-repair', 'electrical'],
    tagline: 'Fixed, not replaced. Most jobs done on the first visit.',
    bio: 'Washing machines, dishwashers, dryers, ovens and rangehoods. I carry the common parts on the van.',
    suburb: 'Norwood',
    years: 19,
    hourly: 105,
    callout: 79,
    minimum: 110,
    rating: 4.3,
    reviews: 41,
    jobs: 203,
    credits: 6,
    tier: 'FREE',
    verified: false,
    pendingVerification: true,
    licence: 'SA-EL-40218',
    insurer: null,
    abn: '30 447 118 005',
    handyman: [],
  },
  {
    name: 'Hannah Wallace',
    business: 'Wallace Plastering',
    trades: ['plastering', 'painting'],
    tagline: 'Patches you will never find again.',
    bio: 'Gyprock, cornice, ceiling repairs and skim coating. Ten years setting walls — if you can see where the patch was, I have not finished.',
    suburb: 'Fremantle',
    years: 10,
    hourly: 90,
    callout: 55,
    minimum: 150,
    rating: 4.8,
    reviews: 33,
    jobs: 121,
    credits: 17,
    tier: 'SUBBIE',
    verified: true,
    homegirl: true,
    licence: 'WA-PL-20119',
    insurer: 'QBE Tradesman',
    abn: '66 220 913 447',
    handyman: ['Wall patching & touch-up paint'],
    intro:
      'Plasterer in Freo. Did my apprenticeship at 29 after a career change, so I know the mature-age route well if anyone is thinking about it.',
    mentor: true,
  },
  {
    name: 'Sam Okafor',
    business: 'Okafor Handyman Services',
    trades: ['handyman', 'glazing', 'appliance-repair'],
    tagline: 'The small stuff, done Saturday morning.',
    bio: 'Weekend and after-hours handyman work for people who are at work all week. Flyscreens, flat-packs, blinds, taps, doors.',
    suburb: 'Joondalup',
    years: 7,
    hourly: 88,
    callout: 45,
    minimum: 88,
    rating: 4.6,
    reviews: 28,
    jobs: 96,
    credits: 14,
    tier: 'SUBBIE',
    verified: true,
    weekends: true,
    licence: null,
    insurer: 'CGU Trade Cover',
    abn: '78 112 663 004',
    handyman: [
      'Flat-pack furniture assembly',
      'Sticking windows & flyscreens',
      'Curtain rails & blinds',
      'Picture & mirror hanging',
      'Pet doors',
      'Leaking taps & washers',
    ],
  },
  {
    name: 'Rita Kalogeropoulos',
    business: 'Rita K Bathrooms & Kitchens',
    trades: ['bathroom-reno', 'kitchen-reno', 'tiling'],
    tagline: 'One tradie who owns the whole renovation.',
    bio: 'Full bathroom and kitchen renovations. I project-manage the lot — demo, waterproofing, tiling, plumbing and sparky trades all booked and sequenced by me.',
    suburb: 'Dandenong',
    years: 21,
    hourly: 140,
    callout: 0,
    minimum: 2000,
    rating: 4.9,
    reviews: 44,
    jobs: 88,
    credits: 35,
    tier: 'MASTER',
    verified: true,
    featured: true,
    homegirl: true,
    licence: 'VIC-DB-U-29014',
    insurer: 'Allianz Trades',
    abn: '55 880 114 227',
    handyman: [],
    intro:
      'Twenty-one years doing bathrooms and kitchens out of Dandenong. I run the whole job so clients only deal with one person. Always looking for reliable tilers and sparkies to sub to.',
    mentor: true,
  },
  {
    name: 'Craig Bartholomew',
    business: 'Bartholomew Pest Control',
    trades: ['pest-control'],
    tagline: 'Termite inspections and the annual spray, done properly.',
    bio: 'Licensed pest technician. Termite inspections, general sprays, rodents and possum-proofing.',
    suburb: 'Southport',
    years: 16,
    hourly: 110,
    callout: 0,
    minimum: 140,
    rating: 4.5,
    reviews: 37,
    jobs: 310,
    credits: 9,
    tier: 'FREE',
    verified: true,
    licence: 'QLD-PMT-55210',
    insurer: 'QBE Tradesman',
    abn: '41 229 007 883',
    handyman: [],
  },
  {
    name: 'Leanne Dwyer',
    business: 'Dwyer Bond Cleaning',
    trades: ['cleaning'],
    tagline: 'Bond back or we come back. No argument.',
    bio: 'End-of-lease and post-build cleaning across Perth. Agents know us, which is half the battle at inspection.',
    suburb: 'Fremantle',
    years: 12,
    hourly: 65,
    callout: 0,
    minimum: 220,
    rating: 4.7,
    reviews: 89,
    jobs: 520,
    credits: 22,
    tier: 'SUBBIE',
    verified: true,
    weekends: true,
    homegirl: true,
    licence: null,
    insurer: 'CGU Trade Cover',
    abn: '92 116 440 771',
    handyman: [],
    intro: 'Bond cleans in Perth since 2013. Six staff, all women. Happy to share our agent checklist with anyone starting out.',
    mentor: true,
  },
  {
    name: 'Tony Ferraro',
    business: 'Ferraro Glass & Screens',
    trades: ['glazing'],
    tagline: 'Cracked pane today, fixed today.',
    bio: 'Window replacement, flyscreens, shower screens and mirrors. Same-day for broken glass wherever possible.',
    suburb: 'Penrith',
    years: 24,
    hourly: 100,
    callout: 65,
    minimum: 130,
    rating: 4.4,
    reviews: 31,
    jobs: 178,
    credits: 11,
    tier: 'FREE',
    verified: false,
    pendingVerification: true,
    licence: null,
    insurer: null,
    abn: '18 774 002 116',
    handyman: ['Sticking windows & flyscreens'],
  },
  {
    name: 'Josh Tuilagi',
    business: 'Tuilagi Removals',
    trades: ['removals', 'cleaning'],
    tagline: 'Two blokes, one truck, nothing broken.',
    bio: 'House moves, hard rubbish, deceased estates and garage clear-outs. We wrap the furniture, not just throw it in.',
    suburb: 'Dandenong',
    years: 8,
    hourly: 130,
    callout: 0,
    minimum: 260,
    rating: 4.6,
    reviews: 55,
    jobs: 267,
    credits: 16,
    tier: 'SUBBIE',
    verified: true,
    weekends: true,
    licence: null,
    insurer: 'Allianz Trades',
    abn: '27 663 118 904',
    handyman: ['Rubbish & green waste runs'],
  },
  {
    name: 'Andrew Beckett',
    business: 'Beckett Heating & Cooling',
    trades: ['air-conditioning', 'electrical'],
    tagline: 'Split systems installed tidy, ducted serviced properly.',
    bio: 'Refrigeration licensed. Split system supply and install, ducted servicing and evaporative cooling repairs.',
    suburb: 'Chermside',
    years: 13,
    hourly: 125,
    callout: 80,
    minimum: 160,
    rating: 4.2,
    reviews: 26,
    jobs: 134,
    credits: 5,
    tier: 'FREE',
    verified: false,
    licence: 'QLD-ARC-L091223',
    insurer: 'QBE Tradesman',
    abn: '63 009 227 118',
    handyman: [],
  },
  {
    name: 'Nadia Haddad',
    business: 'Haddad Handywoman',
    trades: ['handyman', 'carpentry', 'painting'],
    tagline: 'A handywoman for the jobs on the fridge door.',
    bio: 'I do the list — the shelf, the sticking door, the blind that fell down, the tap that drips. Mostly working for older clients and women living on their own who would rather book a woman.',
    suburb: 'Newtown',
    years: 9,
    hourly: 92,
    callout: 40,
    minimum: 92,
    rating: 5.0,
    reviews: 47,
    jobs: 186,
    credits: 29,
    tier: 'GUVNOR',
    verified: true,
    featured: true,
    weekends: true,
    homegirl: true,
    licence: 'NSW-HB-221904',
    insurer: 'CGU Trade Cover',
    abn: '74 118 220 663',
    handyman: [
      'Flat-pack furniture assembly',
      'Shelves, brackets & wall mounting',
      'Picture & mirror hanging',
      'Door adjusting & hanging',
      'Curtain rails & blinds',
      'Leaking taps & washers',
      'Child safety fittings',
      'Odd jobs list (by the hour)',
    ],
    intro:
      'Handywoman in the inner west. Most of my work comes from women who want another woman in the house — there is far more demand than there are of us. Sing out if you want overflow work.',
    mentor: true,
  },
  {
    name: 'Simon Athanasiou',
    business: 'Athanasiou Fencing',
    trades: ['fencing', 'concreting'],
    tagline: 'Colorbond and paling, straight and plumb.',
    bio: 'Fencing contractor. Colorbond, timber paling, pool fencing and gates. Boundary disputes sorted with the neighbour before we start.',
    suburb: 'Parramatta',
    years: 17,
    hourly: 100,
    callout: 0,
    minimum: 350,
    rating: 4.3,
    reviews: 29,
    jobs: 158,
    credits: 13,
    tier: 'FREE',
    verified: true,
    licence: 'NSW-HB-183377',
    insurer: 'QBE Tradesman',
    abn: '36 118 907 442',
    handyman: ['Fence & gate repairs'],
  },
  {
    name: 'Danielle Mbeki',
    business: 'Mbeki Electrical & Solar',
    trades: ['electrical'],
    tagline: 'Switchboards, safety switches and solar done to code.',
    bio: 'A-grade electrician specialising in switchboard upgrades, safety switch installs and solar connections.',
    suburb: 'Blacktown',
    years: 6,
    hourly: 118,
    callout: 70,
    minimum: 150,
    rating: 4.6,
    reviews: 18,
    jobs: 64,
    credits: 20,
    tier: 'SUBBIE',
    verified: true,
    homegirl: true,
    licence: 'NSW-EC-311204',
    insurer: 'Allianz Trades',
    abn: '58 004 771 229',
    handyman: ['Smoke alarm battery swap'],
    intro:
      'Six years out of my apprenticeship, running my own van in western Sydney. Would love a mentor who has been through the first few years of self-employment.',
    seeking: true,
  },
]

export const CLIENTS = [
  { name: 'Margaret Doyle', suburb: 'Parramatta' },
  { name: 'Hamish Fraser', suburb: 'Newtown' },
  { name: 'Priya Raman', suburb: 'Blacktown' },
  { name: 'Bill Hardcastle', suburb: 'Manly' },
  { name: 'Wendy Truong', suburb: 'Footscray' },
  { name: 'Damien O’Rourke', suburb: 'Brunswick' },
  { name: 'Sandra Papadopoulos', suburb: 'Frankston' },
  { name: 'Josh Winterbourne', suburb: 'Chermside' },
  { name: 'Fatima Al-Hassan', suburb: 'Dandenong' },
  { name: 'Col Pritchard', suburb: 'Penrith' },
  { name: 'Elise Marchant', suburb: 'Fremantle' },
  { name: 'Trevor Nakamura', suburb: 'Southport' },
  { name: 'Yvonne Castellano', suburb: 'Norwood' },
  { name: 'Reuben Achebe', suburb: 'Joondalup' },
  { name: 'Lorraine Batchelor', suburb: 'Sutherland' },
  { name: 'Ken Ashworth', suburb: 'Ipswich' },
]

/**
 * Jobs. `status` drives how far the seed takes each one:
 *   OPEN        → bids only
 *   AWARDED     → bids + an accepted bid + escrow payment
 *   COMPLETED   → the above plus two-way reviews
 */
export const JOBS = [
  {
    title: 'Odd jobs list — shelves, sticking door and a dripping tap',
    category: 'handyman',
    size: 'ODD_JOB',
    urgency: 'THIS_WEEK',
    min: 150,
    max: 350,
    status: 'COMPLETED',
    description:
      "Bit of a list that has built up over the summer:\n· Three floating shelves in the lounge (plasterboard wall, brackets already bought)\n· Front door sticks badly in the frame, worse when it's humid\n· Laundry tap drips constantly\n· One blind in the back bedroom has come off its bracket\n\nHappy for it all to be done in one visit. I'm home most days.",
  },
  {
    title: 'Hot water system not heating — no hot water at all',
    category: 'plumbing',
    size: 'HALF_DAY',
    urgency: 'EMERGENCY',
    min: 300,
    max: 1500,
    status: 'COMPLETED',
    description:
      "Rheem gas hot water unit, about 12 years old, on the side of the house. No hot water since last night, pilot light appears to be out and won't relight. Two kids in the house so would like it sorted today if at all possible.",
  },
  {
    title: 'Four downlights and two power points in the kitchen',
    category: 'electrical',
    size: 'HALF_DAY',
    urgency: 'NEXT_FORTNIGHT',
    min: 600,
    max: 1100,
    status: 'COMPLETED',
    description:
      'Kitchen renovation is nearly finished and I need the electrical done. Four LED downlights in the ceiling (existing halogens to come out), plus two double power points on the new island bench. Ceiling access through the manhole in the hallway.',
  },
  {
    title: 'Repaint three bedrooms and the hallway',
    category: 'painting',
    size: 'MULTI_DAY',
    urgency: 'FLEXIBLE',
    min: 2500,
    max: 4500,
    status: 'COMPLETED',
    description:
      'Three bedrooms plus the hallway, all walls and ceilings. Standard 2.4m ceilings, the house is about 25 years old. A few picture hook holes to fill. We will pick the colours, you supply the paint. House will be empty the week you do it.',
  },
  {
    title: 'Gutter clean and check for leaks before winter',
    category: 'roofing',
    size: 'ODD_JOB',
    urgency: 'NEXT_FORTNIGHT',
    min: 200,
    max: 450,
    status: 'COMPLETED',
    description:
      'Single storey brick veneer, gutters full of leaves from the two gums out the front. While you are up there, can you check the flashing near the chimney — there was a small damp patch on the ceiling after the last big rain.',
  },
  {
    title: 'Flat-pack wardrobe and two bookshelves assembled',
    category: 'handyman',
    size: 'ODD_JOB',
    urgency: 'THIS_WEEK',
    min: 120,
    max: 280,
    status: 'COMPLETED',
    description:
      "Moved in last weekend. One three-door wardrobe and two tall bookshelves, all still in boxes. The wardrobe is the fiddly one. I'd also like the bookshelves anchored to the wall — small child in the house.",
  },
  {
    title: 'Bathroom regrout and reseal the shower',
    category: 'tiling',
    size: 'FULL_DAY',
    urgency: 'NEXT_FORTNIGHT',
    min: 450,
    max: 900,
    status: 'AWARDED',
    description:
      'Main bathroom, grout is cracked and discoloured in the shower recess and there is mould in the silicone. Roughly 6 square metres of wall tile. Would like it regrouted and resealed properly rather than painted over.',
  },
  {
    title: 'Fix the back gate — drags on the ground and will not latch',
    category: 'fencing',
    size: 'ODD_JOB',
    urgency: 'FLEXIBLE',
    min: 150,
    max: 400,
    status: 'AWARDED',
    description:
      'Timber paling gate, about 1.8m high. It has dropped on the hinges and now drags on the concrete and will not latch. Posts seem solid. Dog keeps getting out, so it needs to actually latch.',
  },
  {
    title: 'Lawn mowing and hedge trim — fortnightly',
    category: 'landscaping',
    size: 'ODD_JOB',
    urgency: 'THIS_WEEK',
    min: 60,
    max: 140,
    status: 'AWARDED',
    description:
      'Looking for someone regular, fortnightly. Front and back lawn (roughly 300sqm total), edges, and the hedge along the driveway trimmed every second visit. Green waste taken away.',
  },
  {
    title: 'Split system air conditioner install in the lounge',
    category: 'air-conditioning',
    size: 'FULL_DAY',
    urgency: 'THIS_WEEK',
    min: 1800,
    max: 3200,
    status: 'OPEN',
    description:
      'Need a 7-8kW split system supplied and installed in an open-plan lounge/dining, roughly 45 square metres. Single storey, brick veneer, outdoor unit can go on the side of the house about 4 metres from the indoor unit. Quote to include the unit.',
  },
  {
    title: 'Patch three holes in the plasterboard and paint',
    category: 'plastering',
    size: 'ODD_JOB',
    urgency: 'FLEXIBLE',
    min: 200,
    max: 500,
    status: 'OPEN',
    description:
      'Three holes in the hallway wall — biggest is about the size of a dinner plate where a door handle went through, the other two are smaller. Needs patching, sanding and painting to match. I have the leftover paint tin.',
  },
  {
    title: 'Locked out — need the front door lock rekeyed',
    category: 'locksmith',
    size: 'ODD_JOB',
    urgency: 'EMERGENCY',
    min: 120,
    max: 350,
    status: 'OPEN',
    description:
      'Just moved into a rental and the agent could only give us one key. Want the front and back door locks rekeyed to the same key and three copies cut. Also a deadbolt on the laundry door if that is straightforward.',
  },
  {
    title: 'Dishwasher not draining',
    category: 'appliance-repair',
    size: 'ODD_JOB',
    urgency: 'THIS_WEEK',
    min: 100,
    max: 400,
    status: 'OPEN',
    description:
      'Bosch dishwasher, about 6 years old. Leaves a few centimetres of water in the bottom after every cycle. I have cleaned the filter and it has not helped. Would rather repair than replace if it is economic.',
  },
  {
    title: 'Bond clean — three bedroom townhouse',
    category: 'cleaning',
    size: 'FULL_DAY',
    urgency: 'THIS_WEEK',
    min: 350,
    max: 650,
    status: 'OPEN',
    description:
      'Three bed, two bath townhouse, moving out on the 30th. Need a full bond clean including oven, windows inside and out, and the carpets steam cleaned. Agent is pretty particular so I need it done properly.',
  },
  {
    title: 'Full bathroom renovation — small main bathroom',
    category: 'bathroom-reno',
    size: 'LARGE_PROJECT',
    urgency: 'FLEXIBLE',
    min: 12000,
    max: 22000,
    status: 'OPEN',
    description:
      'Main bathroom, roughly 2.4m x 2.1m, completely original from 1988. Want the lot done: strip out, new waterproofing, floor and wall tiles, new vanity, toilet, shower screen and a heated towel rail. Happy to take advice on layout. Looking for one tradie to manage the whole job.',
  },
  {
    title: 'Timber deck — replace rotten boards and re-oil',
    category: 'carpentry',
    size: 'MULTI_DAY',
    urgency: 'NEXT_FORTNIGHT',
    min: 1500,
    max: 3500,
    status: 'OPEN',
    description:
      'Merbau deck, about 30 square metres, ten years old. Maybe fifteen boards are soft or splitting and need replacing. The frame underneath looks fine but worth a check. Then a full sand and re-oil.',
  },
  {
    title: 'Termite inspection before we buy',
    category: 'pest-control',
    size: 'ODD_JOB',
    urgency: 'THIS_WEEK',
    min: 250,
    max: 550,
    status: 'OPEN',
    description:
      'Need a pre-purchase termite inspection on a 1960s weatherboard in the next week, with a written report we can give the bank. Property is currently tenanted so access needs to be arranged with the agent.',
  },
  {
    title: 'Move a two bedroom unit across town',
    category: 'removals',
    size: 'FULL_DAY',
    urgency: 'NEXT_FORTNIGHT',
    min: 600,
    max: 1400,
    status: 'OPEN',
    description:
      'Two bedroom unit, first floor with a lift, moving about 18km. Usual furniture plus a piano (upright, not a grand). Roughly 25 boxes, all packed by us. Need it done on a Saturday.',
  },
  {
    title: 'Cracked window pane in the front bedroom',
    category: 'glazing',
    size: 'ODD_JOB',
    urgency: 'THIS_WEEK',
    min: 150,
    max: 450,
    status: 'OPEN',
    description:
      'Cricket ball through the front bedroom window. Single pane, aluminium frame, roughly 900mm x 600mm. Boarded up with ply for now. Would like it replaced this week before it rains again.',
  },
  {
    title: 'Concrete path down the side of the house',
    category: 'concreting',
    size: 'MULTI_DAY',
    urgency: 'FLEXIBLE',
    min: 2000,
    max: 4500,
    status: 'OPEN',
    description:
      'Want a concrete path about 12 metres long and 1.2 metres wide down the side of the house, from the carport to the back yard. Currently gravel and mud. Needs to drain away from the house. Broom finish is fine.',
  },
  {
    title: 'Handywoman needed — shelves and curtain rails',
    category: 'handyman',
    size: 'ODD_JOB',
    urgency: 'FLEXIBLE',
    min: 120,
    max: 300,
    status: 'OPEN',
    homegirl: true,
    description:
      "I live on my own and would much rather have a woman come to the house. Nothing complicated: two sets of curtain rails, a shelf in the linen cupboard, and a mirror hung in the hallway. All the hardware is bought and sitting in the spare room.",
  },
  {
    title: 'Safety switch keeps tripping',
    category: 'electrical',
    size: 'ODD_JOB',
    urgency: 'EMERGENCY',
    min: 200,
    max: 800,
    status: 'OPEN',
    homegirl: true,
    description:
      "The safety switch has tripped four times in two days, usually when the washing machine is on. I'm home alone with a baby and would prefer a woman electrician if there's one available. Happy to wait a day or two for the right person.",
  },
  {
    title: 'Kitchen splashback tiled',
    category: 'tiling',
    size: 'FULL_DAY',
    urgency: 'NEXT_FORTNIGHT',
    min: 500,
    max: 1200,
    status: 'CANCELLED',
    description:
      'Subway tile splashback behind the kitchen bench, about 4 square metres. Tiles already purchased. Existing splashback is painted plasterboard and needs to come off first.',
  },
  {
    title: 'Pressure wash the driveway and front path',
    category: 'cleaning',
    size: 'ODD_JOB',
    urgency: 'FLEXIBLE',
    min: 150,
    max: 400,
    status: 'COMPLETED',
    description:
      'Concrete driveway and front path, both pretty green with moss after the wet winter. About 60 square metres all up. Outdoor tap available.',
  },
  {
    title: 'Build a pergola over the back patio',
    category: 'carpentry',
    size: 'MULTI_DAY',
    urgency: 'FLEXIBLE',
    min: 4000,
    max: 9000,
    status: 'IN_PROGRESS',
    description:
      'Want a timber pergola over the existing concrete patio, roughly 5m x 4m, attached to the house on one side. Polycarbonate roofing. Council approval already sorted. Looking for something that will still look good in fifteen years.',
  },
  {
    title: 'Replace three power points and check the switchboard',
    category: 'electrical',
    size: 'HALF_DAY',
    urgency: 'THIS_WEEK',
    min: 300,
    max: 700,
    status: 'COMPLETED',
    description:
      'Three power points in the lounge are old and one is loose in the wall. While you are here, can you look at the switchboard — it still has ceramic fuses and I do not think there is a safety switch on the power circuits.',
  },

  {
    title: 'Shelving in the garage and a new laundry door',
    category: 'handyman',
    size: 'HALF_DAY',
    urgency: 'FLEXIBLE',
    suburb: 'Parramatta',
    min: 250,
    max: 600,
    status: 'OPEN',
    description:
      "Two jobs in one visit:\n\u00b7 Heavy-duty shelving along one garage wall, about 4 metres. Brackets and timber not bought yet, happy to take your advice.\n\u00b7 The laundry door is hollow-core and has a hole kicked through the bottom. Replace with a new door, hung and painted.\n\nGarage is a double, plenty of room to work.",
  },
  {
    title: 'Skirting boards replaced in the lounge and hallway',
    category: 'carpentry',
    size: 'FULL_DAY',
    urgency: 'NEXT_FORTNIGHT',
    suburb: 'Newtown',
    min: 700,
    max: 1600,
    status: 'OPEN',
    description:
      'Pulled up the old carpet and the skirting underneath is water damaged in places. About 24 linear metres across the lounge and hallway. Want it replaced with a matching profile, caulked and painted. Floorboards are being sanded the week after, so it needs to be done before then.',
  },
  {
    title: 'Ceiling crack and cornice repair in the front room',
    category: 'plastering',
    size: 'HALF_DAY',
    urgency: 'THIS_WEEK',
    suburb: 'Blacktown',
    min: 300,
    max: 800,
    status: 'OPEN',
    description:
      'Crack running about 1.5 metres across the ceiling in the front room, and the cornice has separated from the wall in the corner. House is 1970s brick veneer. Would like it repaired and set so it does not show once painted.',
  },
  {
    title: 'Exterior repaint — weatherboard front and one side',
    category: 'painting',
    size: 'MULTI_DAY',
    urgency: 'FLEXIBLE',
    suburb: 'Brunswick',
    min: 3500,
    max: 7000,
    status: 'OPEN',
    description:
      'Single storey weatherboard, front elevation and the northern side which cops all the sun. Paint is flaking badly on the north side. Needs scraping, priming where bare, and two top coats. A couple of boards may need replacing — happy to pay for that separately if you find any.',
  },
  {
    title: 'Blocked kitchen drain — water backing up into the sink',
    category: 'plumbing',
    size: 'ODD_JOB',
    urgency: 'EMERGENCY',
    suburb: 'Footscray',
    min: 150,
    max: 600,
    status: 'OPEN',
    description:
      'Kitchen sink is draining very slowly and tonight it backed up completely. Tried a plunger and a drain cleaner from the supermarket, no luck. Single storey, the drain runs out to a gully trap on the side of the house.',
  },
  {
    title: 'Ceiling fan installed in the main bedroom',
    category: 'electrical',
    size: 'ODD_JOB',
    urgency: 'THIS_WEEK',
    suburb: 'Chermside',
    min: 200,
    max: 550,
    status: 'OPEN',
    description:
      'Fan with a light already purchased (Hunter Pacific, DC motor). Replacing an existing batten-fix light fitting, so the wiring is already there, but there is no wall switch for the fan. Ceiling is standard height with roof access nearby.',
  },
  {
    title: 'Overgrown back yard — full clean-up and green waste removal',
    category: 'landscaping',
    size: 'FULL_DAY',
    urgency: 'THIS_WEEK',
    suburb: 'Ipswich',
    min: 400,
    max: 1100,
    status: 'OPEN',
    description:
      'Rental property, tenants have just moved out and the back yard has not been touched in about eight months. Grass is knee high, hedges overgrown, and there is a pile of branches near the back fence. Roughly 400sqm. Needs everything cut back and carted away.',
  },
  {
    title: 'Roof leak above the kitchen after heavy rain',
    category: 'roofing',
    size: 'HALF_DAY',
    urgency: 'EMERGENCY',
    suburb: 'Penrith',
    min: 250,
    max: 1200,
    status: 'OPEN',
    description:
      'Water coming through the kitchen ceiling during the downpour on the weekend, stopped once the rain did. Concrete tile roof, about 20 years old. Need someone to find where it is getting in and fix it before the next lot of rain.',
  },
  {
    title: 'Rekey the house after a break-in',
    category: 'locksmith',
    size: 'ODD_JOB',
    urgency: 'EMERGENCY',
    suburb: 'Fremantle',
    min: 200,
    max: 700,
    status: 'OPEN',
    description:
      'We were broken into on Friday through the back sliding door. Police have been. Need the back door repaired or replaced, all external locks rekeyed, and window locks fitted to the two bedroom windows at the rear.',
  },
  {
    title: 'Oven not heating properly — takes an hour to reach temperature',
    category: 'appliance-repair',
    size: 'ODD_JOB',
    urgency: 'FLEXIBLE',
    suburb: 'Norwood',
    min: 120,
    max: 450,
    status: 'OPEN',
    description:
      'Westinghouse wall oven, about 8 years old. Still heats but takes forever to get up to temperature and the top element does not seem to glow at all. Grill works fine. Would like it looked at before we spend money on a new one.',
  },
  {
    title: 'Fortnightly office clean — small two-room suite',
    category: 'cleaning',
    size: 'ODD_JOB',
    urgency: 'NEXT_FORTNIGHT',
    suburb: 'Joondalup',
    min: 90,
    max: 250,
    status: 'OPEN',
    description:
      'Small office suite, two rooms plus a kitchenette and a shared bathroom. Looking for a fortnightly clean on a Friday afternoon or a weekend: vacuum, mop, bins, kitchen and bathroom. Ongoing arrangement, not a one-off.',
  },
  {
    title: 'Colorbond fence along the back boundary',
    category: 'fencing',
    size: 'MULTI_DAY',
    urgency: 'FLEXIBLE',
    suburb: 'Dandenong',
    min: 2200,
    max: 5000,
    status: 'OPEN',
    description:
      'About 22 metres of back boundary, currently old timber paling that is falling over. Neighbour has agreed to split the cost so the quote needs to be itemised for both of us. Preference for Colorbond in Woodland Grey, 1.8m high. Old fence to be removed and taken away.',
  },
]

export const CLIENT_REVIEW_TEXT = [
  'Turned up when he said he would, which is half the battle these days. Got through the whole list in one visit and the price was exactly what was quoted. Will be using again.',
  'Excellent. Explained what was wrong before touching anything, gave me the option of repair or replace, and did not push the expensive one. Tidy worker.',
  'Great job and a fair price. Only reason it is not five stars is he ran about an hour late, but he did ring to let me know.',
  'Absolutely first class. Cleaned up better than the state he found it in, and came back a week later to check the seal had cured properly. Rare these days.',
  'Did exactly what was asked, on time, no fuss. Quote was itemised so I knew what I was paying for. Recommended.',
  'Very happy. Quoted mid-range, not the cheapest, but the work is clearly better than the cheap quote I got. Worth the extra.',
  'Good work and lovely to deal with. Took the time to explain what she was doing and why, which I appreciated.',
  'Prompt, polite and the job was done properly. Would not hesitate to book again.',
]

export const TRADIE_REVIEW_TEXT = [
  'Job was exactly as described in the posting, which makes quoting a lot easier. Easy access, paid on the day.',
  'Great customer. Had everything ready when I arrived and left me to get on with it. Would work for again any time.',
  'Clear about what was needed and reasonable when I found an extra bit of work underneath. Paid promptly.',
  'No dramas at all. Good communication before the job and on the day.',
  'Lovely people, good cup of tea, and the dog was friendly. Straightforward job.',
]

export const NOTICEBOARD = [
  {
    title: 'Read this first — how the network works',
    category: 'noticeboard',
    pinned: true,
    body: "Welcome. This section is for women working in Australian trades, and it stays private to members.\n\nA few things worth knowing:\n· Jobs where the customer asked for a woman tradesperson appear in your lead feed automatically once you are approved.\n· Your public listing carries the Homegirls badge, which a lot of customers search on specifically.\n· Refer work you cannot take to someone on the members list rather than letting it go.\n· Mentoring is informal. If you have ticked the mentor box, expect the occasional message from an apprentice.\n\nBe decent to each other. Anything out of line, tell the office.",
  },
  {
    title: 'Far more demand for handywomen than there are of us',
    category: 'jobs',
    body: "Just an observation after a busy month: I am turning away two or three jobs a week in the inner west, nearly all of them older women or women living on their own who specifically want a woman in the house. If you are anywhere near Sydney and have capacity, put your hand up — I will pass them straight on.",
  },
  {
    title: 'Cordless SDS — what are people running?',
    category: 'tools',
    body: "My old corded SDS has finally died. Looking at the Makita 18v or the DeWalt equivalent. Mostly masonry anchors and the odd bit of chasing, nothing heroic. Anyone running either of these day to day and got an opinion on battery life?",
  },
  {
    title: 'Mature-age apprenticeship — happy to answer questions',
    category: 'advice',
    body: "I started my plastering apprenticeship at 29 after ten years in hospitality. Best decision I ever made but the first year on adult wages was genuinely tight. If anyone is weighing it up, message me and I will give you the honest version — the money, the sites, the lot.",
  },
  {
    title: 'Pricing fortnightly maintenance rounds',
    category: 'advice',
    body: "Had a few people ask how I price regular garden rounds, so here is roughly what I do: price the first visit as a one-off clean-up at full rate, then the fortnightly at about 60% of that because the work drops off once it is under control. Lock in a minimum of six visits. Density is everything — five jobs in one suburb beats eight spread across the city.",
  },
  {
    title: 'Meet-up — western Sydney, first Thursday',
    category: 'events',
    body: "Informal get-together at the pub in Parramatta, first Thursday of the month from 5.30. No agenda, just a drink and a whinge with people who understand. Six of us last time. All welcome, apprentices especially.",
  },
  {
    title: 'Insurance renewal — shop it around',
    category: 'advice',
    body: "Renewal came in at a 40% increase with no claims. Rang three brokers and got it back under last year's number with better cover. Do not just pay the renewal notice.",
  },
]

export const ENQUIRIES = [
  {
    name: 'Beryl Hutchinson',
    email: 'beryl.hutchinson@example.com',
    phone: '0412 884 019',
    subject: 'A question about a job',
    suburb: 'Sutherland',
    message:
      "I posted a job on Tuesday for gutter cleaning (reference is on the email you sent me) and I have had two quotes. One is a fair bit cheaper than the other. Is there any way of knowing whether the cheap one is any good? I am 78 and I do not want to be taken for a ride.",
    handled: true,
  },
  {
    name: 'Dave Orsini',
    email: 'dave@orsinibuilding.com.au',
    phone: '0433 771 002',
    subject: 'Verify my licence',
    suburb: 'Penrith',
    message:
      'Signed up last week as a builder. I have emailed my licence and insurance certificate to the office address twice now and my profile still says pending. Can someone have a look? I am losing work to verified blokes.',
    handled: false,
  },
  {
    name: 'Rachel Lim',
    email: 'rachel.lim@example.com',
    subject: 'Homegirls network',
    suburb: 'Brunswick',
    message:
      'I am a second year electrical apprentice and I would like to join the Homegirls section. Do I need my own ABN and a full licence, or can apprentices join too?',
    handled: false,
  },
  {
    name: 'Gordon Pethick',
    email: 'g.pethick@example.com',
    phone: '0408 119 553',
    subject: 'A problem with a tradie',
    suburb: 'Ipswich',
    message:
      'The concreter I hired through your site has not been back for nine days and the path is half poured. I have paid a deposit directly to him, not through your escrow. What are my options here?',
    handled: false,
  },
  {
    name: 'Simone Vardy',
    email: 'simone.vardy@example.com',
    subject: 'Billing or membership',
    suburb: 'Fremantle',
    message:
      'I want to drop from the Guvnor plan to Subbie — work has slowed right down over winter. Can I do that mid-month or do I need to wait for the renewal date? Also will I keep the credits I have already got?',
    handled: true,
  },
]
